[versions]
kotlin = "1.9.0"
xemanticOsc = "2.0-SNAPSHOT"
gradleVersionsPlugin = "0.47.0"

[libraries]
xemantic-osc-udp = { module = "com.xemantic.osc:xemantic-osc-udp", version.ref = "xemanticOsc" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
gradle-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
